name: Deploy React.js site to AWS EC2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Add SSH Key
        run: |
          # Create the .ssh directory
          mkdir -p ~/.ssh

          # Save the EC2_KEY into a file and set correct permissions
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Test SSH Connection and Create File
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key_path: ~/.ssh/id_rsa # Use the saved key file path
          script: |
            # Navigate to the home directory
            cd ~

            # Create a text file to confirm successful SSH connection
            echo "This file was created by a GitHub Action" > created_from_github_action.txt
