name: Create File on EC2

on:
  push:
    branches:
      - main # Change if necessary

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Create file on EC2
        env:
          SSH_USER: ubuntu # Use `ec2-user` if necessary
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@13.234.77.56 "echo 'This file was created from GitHub Action' > created_from_githubaction.txt"
